### ISSUE TITLE
[Security] Workflow release.yml is using vulnerable action s-weigand/github-action-template

### ISSUE THREAD

**Issue by igibek** [s-weigand/github-action-template#308]
The workflow release.yml is referencing action s-weigand/github-action-template using references v1. However this reference is missing the commit [b6334571e8eec94855dfbc3f1e168061fdf91b2e](https://github.com/s-weigand/github-action-template/commits/b6334571e8eec94855dfbc3f1e168061fdf91b2e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by s-weigand** [comment]
Invalid same reason as https://github.com/s-weigand/setup-conda/issues/185#issuecomment-1003788511
